print("Deleted the previous one")
print("Day 1 on this one")
print("Day 2 on this one")
print("Day 3 on this one")
print("Day 4 on this one")
print("Day 5 on this one")
print("Day 6 on this one")
print("Day 7 on this one")
print("Day 8 on this one")